services:  
  postgres:
    container_name: "postgres-container-credgem"
    image: "postgres:16"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=credgem # Added to create a default database
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
    networks:
      - "mynetwork"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    container_name: "redis-container-credgem"
    image: "redis:7.2"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "redisdata:/data"
    command: redis-server --appendonly yes
    networks:
      - "mynetwork"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 30

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: "server-container-credgem"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=postgres-container-credgem
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_NAME=credgem
      - REDIS_URL=redis://redis-container-credgem:6379
    networks:
      - "mynetwork"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  admin-panel:
    build: 
      context: ./admin-panel
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://0.0.0.0:8000/api/v1
    environment:
      - VITE_API_URL=http://0.0.0.0:8000/api/v1
    container_name: "admin-panel-container-credgem"
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - server
    networks:
      - "mynetwork"
    restart: unless-stopped

volumes:
  postgresdata:
  redisdata:

networks:
  mynetwork:
    driver: bridge