INSUFFICIENT_BALANCE_ERROR = "Insufficient balance"
DUPLICATE_TRANSACTION_ERROR = "Transaction ID already exists"
BALANCE_NOT_FOUND_ERROR = "Balance not found"
HOLD_TRANSACTION_NOT_FOUND_ERROR = "Hold transaction not found"
HOLD_TRANSACTION_NOT_HELD_ERROR = "Hold transaction is not in held state"
HOLD_AMOUNT_EXCEEDS_ERROR = "Requested debit amount exceeds the held amount"
RELEASE_TRANSACTION_NOT_FOUND_ERROR = "Release transaction not found"
WALLET_NOT_FOUND_ERROR = "Wallet not found"
